services:
  # Redis for caching and sessions (shared)
  redis:
    image: redis:7-alpine
    container_name: uploadparty-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-secure_redis_password}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - uploadparty-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # Frontend (shared; optional, can be deployed separately)
  frontend:
    image: node:20-alpine
    container_name: uploadparty-frontend
    working_dir: /app
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: ${API_URL:-http://localhost:8080}
      REACT_APP_API_URL: ${API_URL:-http://localhost:8080} # compatibility if needed
    volumes:
      - ./site:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - uploadparty-network
    restart: unless-stopped

  # Nginx reverse proxy (shared)
  nginx:
    image: nginx:alpine
    container_name: uploadparty-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - frontend
    networks:
      - uploadparty-network
    restart: unless-stopped

volumes:
  redis_data:
  pg_data:

networks:
  uploadparty-network:
    driver: bridge
