# Air configuration for hot reloading the Go API
# Uses github.com/air-verse/air

# Working directory (run from backend/)
root = "."

tmp_dir = "tmp"

[build]
  # Build command and binary
  cmd = "go build -o ./tmp/main ./cmd/server"
  bin = "./tmp/main"
  full_bin = ""
  # Delay to debounce rapid changes
  delay = 100
  # Send interrupt then kill after 1s on restart
  stop_on_error = true
  kill_delay = 1000

  # Include/Exclude paths
  include_ext = ["go", "tpl", "tmpl", "html", "json", "yaml", "yml"]
  exclude_dir = ["tmp", "vendor", "node_modules", ".git"]
  exclude_regex = ["_test.go$"]

  # Environment file for local dev
  # Air will export these before running the binary
  env_file = [".env"]

[log]
  time = true
  color = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
  app = "white"

[misc]
  # Do not clean tmp dir on exit to speed subsequent starts
  clean_on_exit = false
